version: '3.9'
services:
  weaviate:
    image: semitechnologies/weaviate:1.32.9
    ports:
      - "8081:8080"  # Map host:8081 to container:8080
      - "50051:50051"  # gRPC port
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - DEFAULT_VECTORIZER_MODULE=none
      - CLUSTER_HOSTNAME=localhost
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped

volumes:
  weaviate_data: